name: Latest blog post workflow
on:
  schedule:
    # 1시간마다 실행
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://2jang-dev.tistory.com/rss"
          accept_header: "*/*"
          max_post_count: 5
          date_format: "yyyy-mm-dd"
          template: "$newline- $date [$title]($url)"
          
          title_max_length: 70
          
          committer_username: "2jang"
          committer_email: "jakeecc@naver.com"
