name: Latest blog post workflow
on:
  schedule:
    # 1시간마다 실행
    - cron: '0 * * * *'
  # Actions 탭에서 수동으로 실행
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          # 블로그 RSS 피드 주소
          feed_list: "https://2jang-dev.tistory.com/rss"
          # Tistory 서버 오류 방지를 위한 헤더 설정
          accept_header: "*/*"
          # 표시할 최대 게시물 수
          max_post_count: 5
          # 날짜 포맷
          date_format: "yyyy-mm-dd"
